# Generated by Django 4.1 on 2022-08-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tender_ID', models.IntegerField(max_length=100)),
                ('Tender_Reference_Number', models.IntegerField(max_length=100)),
                ('Form_of_Contract', models.CharField(max_length=200)),
                ('Number_of_Covers', models.IntegerField(max_length=100)),
                ('General_Technical_Evaluation_Allowed', models.CharField(max_length=200)),
                ('Item_Wise_Evaluation_Allowed', models.CharField(max_length=200)),
                ('Payment_Mode', models.CharField(max_length=200)),
            ],
        ),
    ]
