# Generated by Django 4.1 on 2022-08-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENIVIDA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='Number_of_Covers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tender',
            name='Tender_ID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tender',
            name='Tender_Reference_Number',
            field=models.IntegerField(default=0),
        ),
    ]
