# Generated by Django 4.1 on 2022-08-10 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ENIVIDA', '0004_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='Tender_Category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ENIVIDA.category'),
            preserve_default=False,
        ),
    ]
