# Generated by Django 4.1 on 2022-08-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENIVIDA', '0006_tender_tender_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Press',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Press_Release', models.CharField(max_length=200)),
            ],
        ),
    ]
