# Generated by Django 4.1 on 2022-08-12 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ENIVIDA', '0008_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Date_of_Birth',
        ),
    ]
