# Generated by Django 4.1 on 2022-08-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENIVIDA', '0010_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bidder_Name', models.CharField(max_length=500)),
                ('Bidder_Email', models.EmailField(max_length=25)),
                ('Bidder_Mobile', models.CharField(max_length=500)),
                ('Password', models.CharField(max_length=500)),
                ('Company_Name', models.CharField(max_length=500)),
                ('Registration_Number', models.CharField(max_length=500)),
                ('Registered_Address', models.CharField(max_length=1000)),
                ('Partners_or_Directors', models.CharField(max_length=500)),
                ('City', models.CharField(max_length=500)),
                ('State', models.CharField(max_length=500)),
                ('Postal_Code', models.IntegerField(default=0)),
                ('PAN_TAN_Number', models.CharField(max_length=500)),
                ('Estd_Year', models.IntegerField(default=2022)),
                ('Nature_of_Business', models.CharField(max_length=500)),
                ('Legel_Status', models.CharField(max_length=500)),
                ('User_Name', models.CharField(max_length=500)),
                ('User_Gender', models.CharField(max_length=500)),
                ('Deignation', models.CharField(max_length=500)),
                ('User_Mobile', models.CharField(max_length=500)),
            ],
        ),
    ]
