# Generated by Django 4.1 on 2022-08-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENIVIDA', '0011_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Bidder_Name',
            field=models.CharField(default=0, max_length=500),
        ),
    ]
