# Generated by Django 4.1 on 2022-08-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENIVIDA', '0013_alter_user_bidder_email_alter_user_bidder_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Bidder_Name',
            field=models.CharField(max_length=500),
        ),
    ]
