# Generated by Django 4.1 on 2022-08-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENIVIDA', '0018_alter_user_bidder_email_alter_user_bidder_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Bidder_Email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Bidder_Name',
        ),
        migrations.AddField(
            model_name='user',
            name='Biddr_Email',
            field=models.EmailField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='Biddr_Name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
