# Generated by Django 4.1 on 2022-08-12 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ENIVIDA', '0019_remove_user_bidder_email_remove_user_bidder_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Biddr_Email',
            new_name='Bidder_Email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Biddr_Name',
            new_name='Bidder_Name',
        ),
    ]
