# Generated by Django 4.1 on 2022-08-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENIVIDA', '0021_alter_user_bidder_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Bidder_Name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
