# Generated by Django 4.1 on 2022-08-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENIVIDA', '0022_alter_user_bidder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Email',
            field=models.EmailField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='Name',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
