# Generated by Django 4.1 on 2022-08-12 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ENIVIDA', '0023_user_email_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Bidder_Email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Bidder_Name',
        ),
    ]
