# Generated by Django 4.1 on 2022-08-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENIVIDA', '0027_alter_etender_bidder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etender',
            name='Tender_Category',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='etender',
            name='Tender_ID',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='etender',
            name='Tender_Type',
            field=models.CharField(max_length=200),
        ),
    ]
