# Generated by Django 4.1 on 2022-08-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENIVIDA', '0028_alter_etender_tender_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etender',
            name='Bidder_Name',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
