# Generated by Django 4.1 on 2022-08-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENIVIDA', '0029_alter_etender_bidder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etender',
            name='Tender_Category',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='etender',
            name='Tender_ID',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='etender',
            name='Tender_Type',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
