# Generated by Django 4.1 on 2022-08-17 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ENIVIDA', '0030_alter_etender_tender_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etender',
            old_name='Bidder_Name',
            new_name='Biddername',
        ),
    ]
