# Generated by Django 4.1 on 2022-08-17 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ENIVIDA', '0031_rename_bidder_name_etender_biddername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etender',
            name='Tender_Category',
        ),
    ]
