# Generated by Django 4.1 on 2022-08-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENIVIDA', '0033_etender_tender_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etender',
            name='Organization_size',
            field=models.IntegerField(),
        ),
    ]
