# Generated by Django 4.1 on 2022-08-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENIVIDA', '0034_alter_etender_organization_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etender',
            name='Organization_established_Year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='etender',
            name='Proposed_Cost_of_Project',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='etender',
            name='Value_of_Last_Project',
            field=models.IntegerField(),
        ),
    ]
