# Generated by Django 4.1 on 2022-08-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENIVIDA', '0036_remove_etender_organization_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='etender',
            name='Organization_size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
