# Generated by Django 4.1 on 2022-08-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENIVIDA', '0037_etender_organization_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='administrater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admin_Name', models.CharField(default=0, max_length=200)),
                ('Admin_Email', models.EmailField(default=0, max_length=200)),
                ('Admin_Mobile', models.CharField(default=0, max_length=500)),
                ('Admin_Password', models.CharField(default=0, max_length=500)),
            ],
        ),
    ]
