# Generated by Django 4.1 on 2022-08-25 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ENIVIDA', '0038_administrater'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Deignation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='User_Gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='User_Mobile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='User_Name',
        ),
    ]
