# Generated by Django 4.1 on 2022-08-26 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ENIVIDA', '0041_rename_admin_mobile_administrater_aemail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tender',
            name='Status',
        ),
    ]
