# Generated by Django 4.1 on 2022-08-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENIVIDA', '0043_rename_tender_category_etender_bid_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etender',
            name='Organization_established_Year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='etender',
            name='Organization_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='etender',
            name='Proposed_Cost_of_Project',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='etender',
            name='Value_of_Last_Project',
            field=models.IntegerField(default=0),
        ),
    ]
