# Generated by Django 4.1 on 2022-08-26 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ENIVIDA', '0044_alter_etender_organization_established_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etender',
            old_name='Organization_established_Year',
            new_name='orgy',
        ),
    ]
