# Generated by Django 4.1 on 2022-08-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENIVIDA', '0046_remove_etender_organization_size_remove_etender_orgy'),
    ]

    operations = [
        migrations.AddField(
            model_name='etender',
            name='Organization_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='etender',
            name='orgy',
            field=models.IntegerField(default=0),
        ),
    ]
